services:
  postgres:
    image: postgres:latest
    container_name: dev-postgres
    environment:
      POSTGRES_DB: bugbook
      POSTGRES_USER: yaredow
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev-network

volumes:
  pgdata:

networks:
  dev-network:
